name: Generate and Deploy SDK Documentation

on:
  # Only run on pushes to main that affect the SDK
  push:
    branches: [main]
    paths:
      - "sdk/lib/**"
      - "sdk/README.md"
      - "sdk/package.json"
      - "sdk/tsconfig*.json"
      - ".github/workflows/docs.yml"

  # Allow manual triggering
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build documentation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Only fetch the latest commit to save time and bandwidth
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # Cache npm dependencies for faster builds
          cache: "npm"
          cache-dependency-path: "sdk/package-lock.json"

      - name: Install dependencies
        working-directory: ./sdk
        run: npm ci --only=production --ignore-scripts

      - name: Install dev dependencies for docs
        working-directory: ./sdk
        run: npm install --only=dev --no-audit --no-fund

      - name: Generate documentation
        working-directory: ./sdk
        run: npm run docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./sdk/docs"

  # Deploy to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
